# Generated by Django 3.1.1 on 2020-12-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='base_type_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='base1', to='ops.base'),
        ),
        migrations.AddField(
            model_name='operator',
            name='base_type_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='base2', to='ops.base'),
        ),
    ]
