# Generated by Django 3.1.1 on 2020-12-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_clas'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='clas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ops.clas', verbose_name='class'),
        ),
    ]
