# Generated by Django 3.1.1 on 2020-12-07 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0009_auto_20201207_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='ratings',
        ),
        migrations.AddField(
            model_name='comment',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
