# Generated by Django 3.1.1 on 2020-12-07 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0010_auto_20201207_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.operator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('operator', 'user')},
            },
        ),
        migrations.AddField(
            model_name='operator',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_operators', through='ops.Fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
