# Generated by Django 3.1.1 on 2020-12-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0013_auto_20201207_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
